all: DFSMaze.cpp DFSMaze2.cpp
	g++ -Wall -Wextra -std=c++17 -o DFSMaze.exe DFSMaze.cpp
	g++ -Wall -Wextra -std=c++17 -o DFSMaze2.exe DFSMaze2.cpp
go:
	./DFSMaze.exe<DFSMaze.txt
go2:
	./DFSMaze2.exe<DFSMaze.txt
clean:
	rm -f DFSMaze.exe
	rm -f DFSMaze2.exe
